### ISSUE TITLE
--dont-exit-on-error option seems to be broken

### ISSUE THREAD

**Issue by imartisko** [staticafi/symbiotic#127]
Suppose the following input:
```
int main ()
{
        int *a;
        int *b;
        free(a);
        free(a);
        free(b);
        free(b);
}
```
`symbiotic --prp=memsafety --dont-exit-on-error` produces the same output (memory error: invalid pointer: free at line 5) as `symbiotic --prp=memsafety`.

**Comment by mchalupa** [comment]
This is the expected behavior. KLEE terminates a path if there is an error on it. In this program, there is only one path and it is killed on line 5. The `--dont-exit-on-error` switch tells Symbiotic to try to find as many errors (on different paths) as possible. Without this switch, Symbiotic terminates after it finds any (the first) error. For example:
```C
#include <assert.h>
int main(void)
{
        int a = __VERIFIER_nondet_int();
        if (a > 0) {
                assert(0 && "first");
        } else {
                assert(0 && "second");
        }
        return 0;
}
```
If you run Symbiotic without `--dont-exit-on-error`, only one error will be reported (whichever is found first), but with the switch, it should report both.

**Comment by kdudka** [comment]
On Thursday, November 28, 2019 6:54:01 PM CET Marek Chalupa wrote:
> This is the expected behavior. KLEE terminates a path if there is an error
> on it. In this program, there is only one path and it is killed on line 5.

This is perfectly fine.  There is no point to continue with symbolic execution 
on paths where the program would have already crashed.

> If you run Symbiotic without `--dont-exit-on-error`, only one error will be
> reported (whichever is found first), but with the switch, it should report
> both.

That was exactly my expectation, too.  The problem is that it did not work
for me either.  Could you please paste the output you get out of `symbiotic
--dont-exit-on-error` for the above mentioned input program?

**Comment by mchalupa** [comment]
Right, that does not work either. I fixed it in the current development branch. Hopefully, I will merge the master and the devel branches soon.

**Comment by kdudka** [comment]
For those who are surprised by all of sudden missing `--dont-exit-on-error`, the option seems to be on by default since commit 7e32ff83fba7c994354750151632053690d25067.  I think it could have been kept as deprecated or undocummented no-op for compatibility but there are probably not many users relying on symbiotic's CLI yet.

**Comment by kdudka** [comment]
By the way, 8738e5b9a1ff05e66a0facb17d9a57165c6ad3bc seems to work as expected in terms of reporting multiple errors in one run.  Thank you for making it work!
