### ISSUE TITLE
stddef.h is in /usr/lib64 and many of them

### ISSUE THREAD

**Issue by jirislaby** [staticafi/symbiotic#61]
get_include_paths does not work well on my system. I have no `stddef.h` in /usr/lib. Only in /usr/lib64 and many of them:
```
/usr/lib64/clang/3.8.1/include/stddef.h
/usr/lib64/gcc/aarch64-suse-linux/6/include/stddef.h
/usr/lib64/gcc/m68k-suse-linux/6/include/stddef.h
/usr/lib64/gcc/powerpc64-suse-linux/6/include/stddef.h
/usr/lib64/gcc/x86_64-suse-linux/6/include/stddef.h
/usr/lib64/gcc/x86_64-suse-linux/7/include/stddef.h
/usr/lib64/gcc/s390x-suse-linux/6/include/stddef.h
/usr/lib64/gcc/mips-suse-linux/6/include/stddef.h
/usr/lib64/gcc/sparc64-suse-linux/6/include/stddef.h
/usr/lib64/gcc/hppa-suse-linux/6/include/stddef.h
/usr/lib64/gcc/arm-suse-linux-gnueabi/6/include/stddef.h
```

**Comment by jirislaby** [comment]
You may want to grep the `cpp -v` output.

**Comment by mchalupa** [comment]
Yes, the `get_include_paths` needs redesign (or erasure). Maybe the best way would be to add the path to the `stddef.h` that clang generated while building llvm. Or even better - copy that `stddef.h` to install/include, so that symbiotic can find it.

However, on can still export `CPPFLAGS`, `CFLAGS` and `LDFLAGS` variables, Symbiotic should take them into the account (or use --cflags and --cppflags switches)

**Comment by mchalupa** [comment]
> You may want to grep the cpp -v output.

Yes, that should work better (also, it should not bring in any troubles with a custom `stddef.h` that we would carry between different environments, as I suggested in the previous comment)
